### ISSUE TITLE
最高温度错误？

### ISSUE THREAD

**Issue by liyiecho** [jihao/colorfulclouds-hass#1]
![image](https://user-images.githubusercontent.com/5213722/59200874-c7e7f400-8bcb-11e9-8b3a-0998e96f02cd.png)
如果没理解错的话，上面温度应该是最高温度，但是查看json发现是使用avg的，应该把代码里的avg改成max
![image](https://user-images.githubusercontent.com/5213722/59200902-d7673d00-8bcb-11e9-8550-a7298d9ac40a.png)
https://github.com/jihao/colorfulclouds-hass/blob/56e49d331393d587efc5e7bc1da3c733933ada6e/custom_components/colorfulclouds/weather.py#L205

**Comment by jihao** [comment]
Thanks ! Fixed now in version 0.1.2. 
[https://github.com/jihao/colorfulclouds-hass/commit/937e4c3439050896382e10f5b2fbeef4c82d8b44](https://github.com/jihao/colorfulclouds-hass/commit/937e4c3439050896382e10f5b2fbeef4c82d8b44)
